<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.509HhZw' shared service.

return $this->privates['.service_locator.509HhZw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'jwt' => ['services', 'lexik_jwt_authentication.encoder', 'getLexikJwtAuthentication_EncoderService.php', true],
    'passencoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
], [
    'jwt' => '?',
    'passencoder' => '?',
]);
