<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XFEvquR' shared service.

return $this->privates['.service_locator.XFEvquR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'crudSupport' => ['privates', '.errored..service_locator.XFEvquR.App\\Entity\\CrudSupport', NULL, 'Cannot autowire service ".service_locator.XFEvquR": it references class "App\\Entity\\CrudSupport" but no such service exists.'],
], [
    'crudSupport' => 'App\\Entity\\CrudSupport',
]);
