<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PH69jRy' shared service.

return $this->privates['.service_locator.PH69jRy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'security' => ['privates', 'security.helper', 'getSecurity_HelperService.php', true],
    'ser' => ['services', 'serializer', 'getSerializerService', false],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'security' => '?',
    'ser' => '?',
    'validator' => '?',
]);
