<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vqrAPAE' shared service.

return $this->privates['.service_locator.vqrAPAE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'prestatairesRepository' => ['privates', 'App\\Repository\\PrestatairesRepository', 'getPrestatairesRepositoryService.php', true],
], [
    'prestatairesRepository' => 'App\\Repository\\PrestatairesRepository',
]);
