<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ebqm.zx' shared service.

return $this->privates['.service_locator.ebqm.zx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'crudSupportRepository' => ['privates', 'App\\Repository\\CrudSupportRepository', 'getCrudSupportRepositoryService.php', true],
], [
    'crudSupportRepository' => 'App\\Repository\\CrudSupportRepository',
]);
