security:
    encoders:
        App\Entity\User:
            algorithm: auto
        App\Entity\SystemUser:
            algorithm: auto

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\SystemUser
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }