<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Prestataires extends \App\Entity\Prestataires implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'matricule', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'denomination', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'adressePrest', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'contactePrest', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'emailPrest', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'statusPrest', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'image'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'matricule', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'denomination', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'adressePrest', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'contactePrest', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'emailPrest', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'statusPrest', '' . "\0" . 'App\\Entity\\Prestataires' . "\0" . 'image'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Prestataires $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule(string $matricule): \App\Entity\Prestataires
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$matricule]);

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getDenomination(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDenomination', []);

        return parent::getDenomination();
    }

    /**
     * {@inheritDoc}
     */
    public function setDenomination(string $denomination): \App\Entity\Prestataires
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDenomination', [$denomination]);

        return parent::setDenomination($denomination);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressePrest(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressePrest', []);

        return parent::getAdressePrest();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressePrest(string $adresse): \App\Entity\Prestataires
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressePrest', [$adresse]);

        return parent::setAdressePrest($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactePrest(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactePrest', []);

        return parent::getContactePrest();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactePrest(int $contacte): \App\Entity\Prestataires
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactePrest', [$contacte]);

        return parent::setContactePrest($contacte);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailPrest(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailPrest', []);

        return parent::getEmailPrest();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailPrest(string $email): \App\Entity\Prestataires
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailPrest', [$email]);

        return parent::setEmailPrest($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusPrest(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusPrest', []);

        return parent::getStatusPrest();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusPrest(string $status): \App\Entity\Prestataires
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusPrest', [$status]);

        return parent::setStatusPrest($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Prestataires
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

}
