<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.uV6AEjb' shared service.

return $this->privates['.service_locator.uV6AEjb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ser' => ['services', 'serializer', 'getSerializerService', false],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'ser' => '?',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
