<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0If8aRX' shared service.

return $this->privates['.service_locator.0If8aRX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'PE' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'ser' => ['services', 'serializer', 'getSerializerService', false],
], [
    'PE' => '?',
    'ser' => '?',
]);
