<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wvc2RRb' shared service.

return $this->privates['.service_locator.wvc2RRb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ser' => ['services', 'serializer', 'getSerializerService', false],
    'transaction' => ['privates', '.errored..service_locator.wvc2RRb.App\\Entity\\Transactions', NULL, 'Cannot autowire service ".service_locator.wvc2RRb": it references class "App\\Entity\\Transactions" but no such service exists.'],
    'transactionsRepository' => ['privates', 'App\\Repository\\TransactionsRepository', 'getTransactionsRepositoryService.php', true],
], [
    'ser' => '?',
    'transaction' => 'App\\Entity\\Transactions',
    'transactionsRepository' => 'App\\Repository\\TransactionsRepository',
]);
