<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9Zq0_OY' shared service.

return $this->privates['.service_locator.9Zq0_OY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'prestataire' => ['privates', '.errored..service_locator.9Zq0_OY.App\\Entity\\Prestataires', NULL, 'Cannot autowire service ".service_locator.9Zq0_OY": it references class "App\\Entity\\Prestataires" but no such service exists.'],
], [
    'prestataire' => 'App\\Entity\\Prestataires',
]);
