<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.firewall.map.config.system' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

return $this->privates['security.firewall.map.config.system'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('system', 'security.user_checker', '.security.request_matcher.ZI1wPuA', true, true, 'security.user.provider.concrete.app_user_provider', NULL, 'lexik_jwt_authentication.jwt_token_authenticator', NULL, NULL, [0 => 'guard'], NULL);
