<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YrB6OhQ' shared service.

return $this->privates['.service_locator.YrB6OhQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'passencoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
], [
    'passencoder' => '?',
]);
