<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.AB.nykr' shared service.

return $this->privates['.service_locator.AB.nykr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ser' => ['services', 'serializer', 'getSerializerService', false],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'ser' => '?',
    'validator' => '?',
]);
