<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Xf27W9Q' shared service.

return $this->privates['.service_locator.Xf27W9Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'validator' => ['privates', 'api_platform.validator', 'getApiPlatform_ValidatorService.php', true],
], [
    'validator' => '?',
]);
