<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xcOLqs6' shared service.

return $this->privates['.service_locator.xcOLqs6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ser' => ['services', 'serializer', 'getSerializerService', false],
    'systemUserRepository' => ['privates', 'App\\Repository\\SystemUserRepository', 'getSystemUserRepositoryService.php', true],
], [
    'ser' => '?',
    'systemUserRepository' => 'App\\Repository\\SystemUserRepository',
]);
