<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nlXHtzo' shared service.

return $this->privates['.service_locator.nlXHtzo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'prestataire' => ['privates', '.errored..service_locator.nlXHtzo.App\\Entity\\Prestataires', NULL, 'Cannot autowire service ".service_locator.nlXHtzo": it references class "App\\Entity\\Prestataires" but no such service exists.'],
    'prestatairesRepository' => ['privates', 'App\\Repository\\PrestatairesRepository', 'getPrestatairesRepositoryService.php', true],
], [
    'prestataire' => 'App\\Entity\\Prestataires',
    'prestatairesRepository' => 'App\\Repository\\PrestatairesRepository',
]);
