<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJR7Zp0t\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJR7Zp0t/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJR7Zp0t.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJR7Zp0t\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerJR7Zp0t\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'JR7Zp0t',
    'container.build_id' => '1c992a7e',
    'container.build_time' => 1565019619,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJR7Zp0t');
