<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIsGs4wh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIsGs4wh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIsGs4wh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIsGs4wh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIsGs4wh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IsGs4wh',
    'container.build_id' => '5d66e3af',
    'container.build_time' => 1566471974,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIsGs4wh');
