<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container95oWZzv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container95oWZzv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container95oWZzv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container95oWZzv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container95oWZzv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '95oWZzv',
    'container.build_id' => '19d57010',
    'container.build_time' => 1565749109,
], __DIR__.\DIRECTORY_SEPARATOR.'Container95oWZzv');
